### ISSUE TITLE
kasparov.ru

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#182]
Hi, could you please remove this filter (or please move to Fanboys Social Blocking list) or add an exception for `kasparov.ru` on this filter : `||connect.facebook.net/ru_RU/*.js#xfbml` it removes the Facebook comments functionality of the website. You can see an example right [here](https://kasparov.ru/material.php?id=6496C095B6F57)
right (without ABP) / left (with ABP) 

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/33602691/cf7b201f-cfc1-48b5-b32f-0c1c719d93b1)

</details>

Using ABP Chrome extension with ABP Filter and RuAdList + Easy List and Allow nonintrusive advertising 
Thank you in advance for looking into this 🤗

**Comment by dimisa-RUAdList** [comment]
I added this rule not to block facebook, but to restore functionality to those sites that use facebook network requests.

In Russia, Facebook is considered a banned organization and providers, fulfilling the will of the law, are forced to block Facebook network requests. Because of this, sites that use such requests either experience endless loading, or they break down altogether.

Thus, the removal of this rule will lead to the breakdown of a huge number of sites, including `kasparov.ru`.

**Comment by eporubin** [comment]
Hi @dimisa-RUAdList Could you please confirm that the page `https://kasparov.ru/material.php?id=6496C095B6F57` is lagging or the website is crushing without this rule. ( As I can't test out with RU location) 
Thank you in advance

**Comment by dimisa-RUAdList** [comment]
At the moment this site does not work in Russia. Most likely, a stricter check of the execution of existing locks by providers has now been introduced. The site was added to the registry a long time ago: https://reestr.rublacklist.net/en/?q=kasparov.ru, but stopped working just now. Therefore, it is not clear how waiting for blocked Facebook network requests affects the operation of the site.

**Comment by eporubin** [comment]
I see, the think is I have checked most of the websites on which hits for this filters were registered in the past, but most of them do not have anymore Facebook network. 
And if anyway `kasparov.ru` is blocked in Russia, this filter rule affects the page for Russian readers in other locations. 
Is there any other example of a domain crushing without this filter?

**Comment by dimisa-RUAdList** [comment]
It looks like the filter is still up to date and does exactly the job it was added to do. Without it, there is an endless loading.

Example: 
`https://vz.ru/world/2023/6/29/1218828.html`
`https://urbc.ru/1068121349-obem-vydannyh-na-yuzhnom-urale-avtokreditov-za-god-vyros-na-75.html`

For the vast majority of users from Russia, the Facebook comments plugin is not available and its use only leads to endless loading. And those users who have access to Facebook do not have a Russian location. Thus, commenting will represent the opinion of users of a third-party location, which makes no sense on Russian sites, since it does not reflect the opinion of the target audience.

I can make an exception for kasparov.ru, since that site is still unavailable, but that would set a precedent to break the trend towards a commenting system that doesn't harm the functioning of the resources and is still accessible to Russian users.

**Comment by eporubin** [comment]
@dimisa-RUAdList  could you please add an exception for `kasparov.ru` as the incident we had was reported by a user outside Russia using the list. 
The page itself it's blocked in Russia anyway already so I do not see any reasons why people outside Russia using the list should experience this False Positive outcome. If they are annoyed by the any Social Media widget they have the choice of enabling the Fanboy Social Blocking List. 
Thank you in advance for understanding.

**Comment by dimisa-RUAdList** [comment]
https://kasparov.ru/material.php?id=6496C095B6F57
