### ISSUE TITLE
windowsbulletin.com

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/ruadlist#29]
anti adb on `http://windowsbulletin.com/ru/how-to-center-an-app-window-on-windows-10/`
originally reported in https://github.com/AdguardTeam/AdguardFilters/issues/95993

**Comment by dimisa-RUAdList** [comment]
`@@||windowsbulletin.com/$generichide`
`windowsbulletin.com#?#p:-abp-has(> a[href^="http://www.reimageplus.com/"])`
This is an international site, so instead of adding rules for it to each regional filter (like RU AdList), need to add them to EasyList. You can report it here: https://github.com/easylist/easylist/issues
