### ISSUE TITLE
pravda.com.ua, eurointegration.com.ua

### ISSUE THREAD

**Issue by alxxjd** [easylist/ruadlist#327]
#### Описание проблемы (Description of the problem):

<details>
<summary>pravda.com.ua</summary>

<img width="1825" alt="image" src="https://github.com/user-attachments/assets/35eba902-4704-437f-82d2-33566493698c">

</details>

<details>
<summary>eurointegration</summary>

<img width="1818" alt="image" src="https://github.com/user-attachments/assets/24443976-0bb3-4364-a30d-d15bbe8ed3ca">

</details>

#### Конфигурация (Configuration):

- OS/version: Mac, 14.6.1
- Browser/version: Chrome/127.0.6533.120
- Ad block extension/version: Adblock Plus 4.5.1

#### Используемые фильтры (Used filters):
<details>
<summary>I used only <b>RU, UA, UZ, KZ+EasyList</b> Filter</summary>

<img width="1261" alt="image" src="https://github.com/user-attachments/assets/4553641f-3987-4f29-8efb-e39448bfd354">
</details>

**Comment by dimisa-RUAdList** [comment]
You have broken the work of Adblock Plus by disabling the basic filter ABP Filters.

**Comment by dimisa-RUAdList** [comment]
On my side, the problem does not repeat itself. On your side, it only repeats itself because you intentionally provoked it. Due to the peculiarities of mv3, disabling and then enabling filters within one session can lead to the browser deleting the instructions received from the extension, but not having time to record them when the filter is enabled. To restore the operation of a newly connected filter, you almost always need to restart the browser, and sometimes even reinstall the extension. Thus, you intentionally break its operation in a way that is not used in real operation.

**Comment by dimisa-RUAdList** [comment]
This is not an extension error, but a deliberate failure provoked by you. As I wrote earlier, after disabling and then enabling filters, you may need to reinstall the extension with a browser restart. This is a feature of ALL mv3 extensions, not just ABP. Additionally, this is aggravated by the fact that the target rule is in the diff patching list, which loads even slower than the rest of the extension instructions. When the rule gets into the main list (with version 4.5.2, in about a week), even with your method, it will be difficult to provoke a breakdown of these sites.
