### ISSUE TITLE
sdamgia.ru

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#81]
User complains that the buttons on the site `https://math-ege.sdamgia.ru/manual` VK bot and tg bot ar not working.

The problem is caused by the filter: `sdamgia.ru#@#a[href][style] > img[src*="/get_file?id="]`
<details>
<summary>Screenshot(s)</summary>

![upload](https://user-images.githubusercontent.com/65717387/190415063-5cc81875-667d-49c0-9c3f-980e155ba496.png)

</details>

Besides that it's possible to see some ad banners at the footer and left side.

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/752b6f4d94cb0f69d194174efa10631b55514859

As for unblocked banners, at the moment Adblock Plus does not have the necessary functionality for those cases when the resources are [problematic](https://github.com/abp-filters/abp-filters-anti-cv/issues/109) and use aggressive methods of circumvention. Perhaps after the release of the MB3 version, when the developers have more time, this will change. Until this happens, we recommend using [RU AdList JS Fixes](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes).

**Comment by dimisa-RUAdList** [comment]
@felippesantos46 
> User complains that the buttons on the site https://math-ege.sdamgia.ru/manual VK bot and tg bot ar not working.

Who is this user and how and where was the complaint sent? 

Over the past 7 years, the webmaster of this site has been deliberately doing everything to make it impossible to work with the enabled ad blocker.

The changes that have been made to the layout clearly indicate that the goal is to substitute elements under some rules from the filters.

We cannot fix this as the first step will always be up to the webmaster.

The fact that instead of disabling the blocker, which actually does almost nothing there anyway, a complaint is sent, indicates that it is not the user who is behind it, but the webmaster himself.

If you receive similar complaints again in the future, please direct users here: https://forums.lanik.us/viewforum.php?f=102
